[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/equipe/yoan-brazy/nos-projets/index.html"
to = "/equipe/yoan-brazy/projets/"

[[redirects]]
from = "/nos-projets/2021-05-01-tu-flippes/index.html"
to = "/projets/2021-05-01-tu-flippes/"

[[redirects]]
from = "/projets/conseil/projet-3/index.html"
to = "/projets/conseil/hyrdo/"

[[redirects]]
from = "/projets/projet-2/index.html"
to = "/projets/etude/desintensification-agriculture-ile-de-france/"

[[redirects]]
from = "/notre-equipe/yoan-brazy/index.html"
to = "/equipe/yoan-brazy/"

[[redirects]]
from = "/yoan-brazy/index.html"
to = "/equipe/yoan-brazy/"

[[redirects]]
from = "/projets-2/projet-2/index.html"
to = "/projets/etude/desintensification-agriculture-ile-de-france/"

[[redirects]]
from = "/nos-projets/2024-01-25-hydrocarbures-diversification-et-redirection/index.html"
to = "/projets/2020-01-25-hydrocarbures-diversification-et-redirection/"

[[redirects]]
from = "/projets-2/projet-3/index.html"
to = "/projets/conseil/hyrdo/"

[[redirects]]
from = "/equipe-repentie/index.html"
to = "/equipe/"

[[redirects]]
from = "/projet-3/index.html"
to = "/projets/conseil/hyrdo/"

[[redirects]]
from = "/yoan-brazy/projets/index.html"
to = "/equipe/yoan-brazy/projets/"

[[redirects]]
from = "/nos-projets/etudes/index.html"
to = "/projets/etudes/"

[[redirects]]
from = "/nos-projets/2024-02-01-2807-ne-depassons-pas-les-limites/index.html"
to = "/projets/2024-02-01-2807-ne-depassons-pas-les-limites/"

[[redirects]]
from = "/equipe-repentie/equipe-editoriale/index.html"
to = "/equipe/equipe-editoriale/"

[[redirects]]
from = "/nos-projets/2021-07-01-enseignement-superieur/index.html"
to = "/projets/2021-07-01-enseignement-superieur/"

[[redirects]]
from = "/projets/etude/projet-2/index.html"
to = "/projets/etude/desintensification-agriculture-ile-de-france/"

[[redirects]]
from = "/lecole-buissonniere/index.html"
to = "/projets/eveil/lecole-buissonniere/"

[[redirects]]
from = "/projets-1/index.html"
to = "/nos-projets/"

[[redirects]]
from = "/nos-projets/2020-01-25-hydrocarbures-diversification-et-redirection/index.html"
to = "/projets/2020-01-25-hydrocarbures-diversification-et-redirection/"

[[redirects]]
from = "/nos-projets/conseil/index.html"
to = "/projets/conseil/"

[[redirects]]
from = "/nos-projets/2023-10-01-shabiller-a-4c/index.html"
to = "/projets/2023-10-01-shabiller-a-4c/"

[[redirects]]
from = "/projets-2/projet-1/index.html"
to = "/projets/eveil/redir-ecologique-dirigeants/"

[[redirects]]
from = "/nos-projets/2023-10-10-peut-on-assurer-un-monde-qui-seffondre/index.html"
to = "/projets/2023-10-10-peut-on-assurer-un-monde-qui-seffondre/"

[[redirects]]
from = "/nos-projets/2024-01-29-tribunes-et-articles/index.html"
to = "/projets/2024-01-29-tribunes-et-articles/"

[[redirects]]
from = "/audit-de-resilience-environnementale/index.html"
to = "/projets/conseil/audit-de-resilience-environnementale/"

[[redirects]]
from = "/eveil/index.html"
to = "/projets/eveil/"

[[redirects]]
from = "/nos-projets/2023-11-11-ooonehealth/index.html"
to = "/projets/2024-02-01-ooonehealth/"

[[redirects]]
from = "/nos-projets/2021-09-01-lecole-buissonniere-x-onestpret/index.html"
to = "/projets/2021-09-01-lecole-buissonniere-x-onestpret/"

[[redirects]]
from = "/equipe-editoriale/index.html"
to = "/equipe/equipe-editoriale/"

[[redirects]]
from = "/nos-projets/2023-11-01-audit-de-resilience-environnementale/index.html"
to = "/projets/2023-11-01-audit-de-resilience-environnementale/"

[[redirects]]
from = "/projets/redir-ecologique-dirigeants/index.html"
to = "/projets/eveil/redir-ecologique-dirigeants/"

[[redirects]]
from = "/projets/conseil/redir-ecologique-dirigeants/index.html"
to = "/projets/eveil/redir-ecologique-dirigeants/"

[[redirects]]
from = "/nos-projets/2021-06-01-conferences-interventions/index.html"
to = "/projets/2021-06-01-conferences-interventions/"

[[redirects]]
from = "/actualites/index.html"
to = "/projets/"

[[redirects]]
from = "/projets/etude/assurer-monde-effondre/index.html"
to = "/projets/etude/desintensification-agriculture-ile-de-france/"

[[redirects]]
from = "/nos-projets/2023-11-01-2807-ne-depassons-pas-les-limites/index.html"
to = "/projets/2024-02-01-2807-ne-depassons-pas-les-limites/"

[[redirects]]
from = "/nos-projets/2023-09-10-deviations-plastiques-x-plastic-odyssey/index.html"
to = "/projets/2023-09-10-deviations-plastiques-x-plastic-odyssey/"

[[redirects]]
from = "/projets/projet-3/index.html"
to = "/projets/conseil/hyrdo/"

[[redirects]]
from = "/projets-2/index.html"
to = "/projets/"

[[redirects]]
from = "/notre-equipe/yoan-brazy/nos-projets/index.html"
to = "/equipe/yoan-brazy/projets/"

[[redirects]]
from = "/etude/index.html"
to = "/projets/etude/"

[[redirects]]
from = "/notre-equipe-1/index.html"
to = "/notre-equipe/"

[[redirects]]
from = "/nos-projets/eveil/index.html"
to = "/projets/eveil/"

[[redirects]]
from = "/projets-2/redir-ecologique-dirigeants/index.html"
to = "/projets/eveil/redir-ecologique-dirigeants/"

[[redirects]]
from = "/nos-projets/2024-02-01-ooonehealth/index.html"
to = "/projets/2024-02-01-ooonehealth/"

[[redirects]]
from = "/nos-projets/2023-10-01-redirection-ecologique-et-jeunes-dirigeantes/index.html"
to = "/projets/2023-10-01-redirection-ecologique-et-jeunes-dirigeantes/"

